### PR TITLE
Stop setting prefix

### PR DESCRIPTION
**Pull request by mmlb**
Its dead code.

### CODE REVIEW

**Comment by mmlb** [comment]
Also broken when I use it in nix, though I don't think that matters. Not sure how 2 dirnames ever worked right, maybe if the symlink target wasn't a full path?

**Comment by mmlb** [comment]
ping to @oscaredel @ravanscafi as approvers to recently merged PRs and @niels-s as the author of https://github.com/blendle/kns/pull/8

**Review by koenbollen — APPROVED** [review]
Looks good to me. 👍🏻

**Comment by oscaredel** [comment]
> ping to @oscaredel @ravanscafi as approvers to recently merged PRs and @niels-s as the author of #8

Hi Manuel, I don't work here anymore. Perhaps @joosterman et al. can take a look.

**Review by joosterman — APPROVED** [review]

**Comment by mmlb** [comment]
:woop:!

**Pull request merged**
